# Generated by Django 5.2.11 on 2026-04-26 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OddsApiUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sport', models.CharField(choices=[('cbb', 'CBB'), ('cfb', 'CFB'), ('mlb', 'MLB'), ('college_baseball', 'College Baseball'), ('golf', 'Golf'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('endpoint', models.CharField(max_length=512)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('credits_used', models.IntegerField(blank=True, null=True)),
                ('credits_remaining', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='ops_oddsapi_timesta_1e4067_idx'), models.Index(fields=['sport', '-timestamp'], name='ops_oddsapi_sport_faf52a_idx'), models.Index(fields=['status_code', '-timestamp'], name='ops_oddsapi_status__3595b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CronRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.CharField(db_index=True, max_length=120)),
                ('trigger', models.CharField(choices=[('cron', 'Scheduled Cron'), ('manual', 'Manual'), ('deploy', 'Deploy Startup')], default='cron', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial Success')], default='running', max_length=10)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('stdout_tail', models.TextField(blank=True, default='')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cron_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='ops_cronrun_started_110f27_idx'), models.Index(fields=['command', '-started_at'], name='ops_cronrun_command_d8ec9d_idx'), models.Index(fields=['status', '-started_at'], name='ops_cronrun_status_ba2177_idx')],
            },
        ),
    ]
