# Generated by Django 5.2.11 on 2026-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('odds_api', 'The Odds API'), ('espn', 'ESPN Fallback')], max_length=20, unique=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('last_open_reason', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Health',
                'verbose_name_plural': 'Provider Health',
                'ordering': ['provider'],
            },
        ),
    ]
