# Generated by Django 5.2.11 on 2026-02-08 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='golfevent',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='golfevent',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GolfOddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('sportsbook', models.CharField(default='consensus', max_length=50)),
                ('outright_odds', models.IntegerField(help_text='American format odds')),
                ('implied_prob', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='golf.golfevent')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='golf.golfer')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
