# Generated by Django 5.2.11 on 2026-02-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfer_external_id_golfevent_external_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfer',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='golfer',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='golfer',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
