# Generated by Django 5.2.11 on 2026-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_alter_golfer_options_golfer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfoddssnapshot',
            name='movement_class',
            field=models.CharField(blank=True, choices=[('noise', 'Noise'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('sharp', 'Sharp Action')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='golfoddssnapshot',
            name='movement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='golfoddssnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('raw', 'Raw Pull'), ('significant', 'Significant Move'), ('closing', 'Closing Line'), ('bet_context', 'Bet Context')], db_index=True, default='raw', max_length=20),
        ),
        migrations.AddIndex(
            model_name='golfoddssnapshot',
            index=models.Index(fields=['event', 'golfer', '-captured_at'], name='golf_golfod_event_i_f4c5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='golfoddssnapshot',
            index=models.Index(fields=['snapshot_type', '-captured_at'], name='golf_golfod_snapsho_587577_idx'),
        ),
    ]
