# Generated by Django 5.2.11 on 2026-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_golfoddssnapshot_odds_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfoddssnapshot',
            name='is_derived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
