# Generated by Django 5.2.11 on 2026-02-07 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_picture'),
        ('cbb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_cbb_conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbb.conference'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_cbb_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbb.team'),
        ),
    ]
