# Generated by Django 5.2.11 on 2026-02-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_timezone_userprofile_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_data',
            field=models.TextField(blank=True, default='', help_text='Base64-encoded data URI for profile picture (stored in DB, no filesystem needed)'),
        ),
    ]
