# Generated by Django 5.2.11 on 2026-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_persona',
            field=models.CharField(choices=[('analyst', 'Analyst (neutral, professional)'), ('new_york_bookie', 'New York Bookie (blunt, street-smart)'), ('southern_commentator', 'Southern Commentator (folksy, confident)'), ('ex_player', 'Ex-Player (direct, experiential)')], default='analyst', max_length=25),
        ),
    ]
