# Generated by Django 5.2.11 on 2026-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_favorite_golfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpreset',
            name='pitcher_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='usermodelconfig',
            name='pitcher_weight',
            field=models.FloatField(default=1.0),
        ),
    ]
