# Generated by Django 5.2.11 on 2026-02-07 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cfb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sportsbook', models.CharField(blank=True, max_length=50)),
                ('total_odds', models.CharField(blank=True, max_length=20)),
                ('implied_probability', models.FloatField(blank=True, null=True)),
                ('house_probability', models.FloatField(blank=True, null=True)),
                ('user_probability', models.FloatField(blank=True, null=True)),
                ('correlation_risk', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='low', max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParlayLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('spread', 'Spread'), ('moneyline', 'Moneyline'), ('total', 'Total')], max_length=10)),
                ('selection', models.CharField(max_length=100)),
                ('odds', models.CharField(blank=True, max_length=20)),
                ('market_prob', models.FloatField(blank=True, null=True)),
                ('house_prob', models.FloatField(blank=True, null=True)),
                ('user_prob', models.FloatField(blank=True, null=True)),
                ('same_game_group', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfb.game')),
                ('parlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='parlays.parlay')),
            ],
        ),
    ]
