# Generated by Django 5.2.11 on 2026-02-07 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbb', '0001_initial'),
        ('cfb', '0001_initial'),
        ('parlays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlayleg',
            name='cbb_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbb.game'),
        ),
        migrations.AlterField(
            model_name='parlayleg',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfb.game'),
        ),
    ]
