# Generated by Django 5.2.11 on 2026-02-08 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_temperature', models.FloatField(default=0.0, help_text='OpenAI temperature (0 = deterministic/factual, 0.3 = slight variation, 1.0+ = creative). Default: 0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('ai_max_tokens', models.IntegerField(default=800, help_text='Maximum tokens in AI response. Default: 800', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(4000)])),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
