# Generated by Django 5.2.11 on 2026-04-21 01:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbb', '0003_team_primary_color'),
        ('cfb', '0003_team_primary_color'),
        ('college_baseball', '0001_initial'),
        ('core', '0001_initial'),
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('cfb', 'College Football'), ('cbb', 'College Basketball'), ('mlb', 'MLB'), ('college_baseball', 'College Baseball')], max_length=20)),
                ('bet_type', models.CharField(choices=[('moneyline', 'Moneyline'), ('spread', 'Spread'), ('total', 'Total')], max_length=10)),
                ('pick', models.CharField(max_length=200)),
                ('line', models.CharField(blank=True, max_length=32)),
                ('odds_american', models.IntegerField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('model_edge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('model_source', models.CharField(choices=[('house', 'House Model'), ('user', 'User Model')], default='house', max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cbb_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cbb.game')),
                ('cfb_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cfb.game')),
                ('college_baseball_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='college_baseball.game')),
                ('mlb_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='mlb.game')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sport', '-created_at'], name='core_bettin_sport_f6447e_idx')],
            },
        ),
    ]
