# Generated by Django 5.2.11 on 2026-04-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bettingrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingrecommendation',
            name='status',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('not_recommended', 'Not Recommended')], default='recommended', max_length=20),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='status_reason',
            field=models.CharField(blank=True, choices=[('', ''), ('low_edge', 'Low Edge'), ('high_juice', 'High Juice Risk'), ('marginal', 'Marginal')], default='', max_length=20),
        ),
    ]
