# Generated by Django 5.2.11 on 2026-04-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bettingrecommendation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingrecommendation',
            name='market_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='movement_class',
            field=models.CharField(blank=True, choices=[('', ''), ('moderate', 'Moderate'), ('strong', 'Strong'), ('sharp', 'Sharp Action')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='movement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='movement_supports_pick',
            field=models.BooleanField(default=False),
        ),
    ]
