# Generated by Django 5.2.11 on 2026-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bettingrecommendation_market_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingrecommendation',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bettingrecommendation',
            name='status_reason',
            field=models.CharField(blank=True, choices=[('', ''), ('low_edge', 'Low Edge'), ('high_juice', 'High Juice Risk'), ('marginal', 'Marginal'), ('derived_odds', 'Derived Odds')], default='', max_length=20),
        ),
    ]
