# Generated by Django 5.2.11 on 2026-04-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bettingrecommendation_is_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingrecommendation',
            name='lane',
            field=models.CharField(choices=[('core', 'Core'), ('qualified', 'Qualified'), ('pass', 'Pass')], db_index=True, default='pass', max_length=10),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='risk_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
