# Generated by Django 5.2.11 on 2026-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bettingrecommendation_lane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingrecommendation',
            name='extreme_disagreement',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='final_model_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='market_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='raw_model_prob',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
