# Generated by Django 5.2.11 on 2026-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bettingrecommendation_extreme_disagreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingrecommendation',
            name='shadow_active_mode',
            field=models.CharField(blank=True, choices=[('', ''), ('static', 'Static (team.rating)'), ('elo', 'Dynamic Elo')], default='', help_text='Rating mode active when this row was persisted.', max_length=10),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='shadow_alt_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bettingrecommendation',
            name='shadow_alt_mode',
            field=models.CharField(blank=True, choices=[('', ''), ('static', 'Static (team.rating)'), ('elo', 'Dynamic Elo')], default='', help_text='Rating mode the shadow_alt_data represents.', max_length=10),
        ),
    ]
