# Generated by Django 5.2.11 on 2026-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bettingrecommendation_shadow_active_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingrecommendation',
            name='feature_contributions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
