# Generated by Django 5.2.11 on 2026-04-19 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_pitch', models.DateTimeField()),
                ('neutral_site', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('pitchers_updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(blank=True, choices=[('espn', 'ESPN'), ('odds_api', 'Odds API'), ('ncaa', 'NCAA'), ('manual', 'Manual')], default='', max_length=30)),
            ],
            options={
                'ordering': ['first_pitch'],
            },
        ),
        migrations.CreateModel(
            name='StartingPitcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(blank=True, choices=[('espn', 'ESPN'), ('odds_api', 'Odds API'), ('ncaa', 'NCAA'), ('manual', 'Manual')], default='', max_length=30)),
                ('throws', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Switch')], default='', max_length=1)),
                ('era', models.FloatField(blank=True, null=True)),
                ('whip', models.FloatField(blank=True, null=True)),
                ('k_per_9', models.FloatField(blank=True, null=True)),
                ('innings_pitched', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=50.0)),
                ('stats_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('sportsbook', models.CharField(default='consensus', max_length=50)),
                ('market_home_win_prob', models.FloatField()),
                ('market_away_win_prob', models.FloatField(blank=True, null=True)),
                ('spread', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('moneyline_home', models.IntegerField(blank=True, null=True)),
                ('moneyline_away', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='college_baseball.game')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_pitcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='college_baseball.startingpitcher'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_pitcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='college_baseball.startingpitcher'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('rating', models.FloatField(default=50.0)),
                ('primary_color', models.CharField(blank=True, default='', max_length=7)),
                ('abbreviation', models.CharField(blank=True, default='', max_length=5)),
                ('external_id', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(blank=True, choices=[('espn', 'ESPN'), ('odds_api', 'Odds API'), ('ncaa', 'NCAA'), ('manual', 'Manual')], default='', max_length=30)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='college_baseball.conference')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='startingpitcher',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitchers', to='college_baseball.team'),
        ),
        migrations.CreateModel(
            name='InjuryImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='college_baseball.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_baseball.team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='college_baseball.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='college_baseball.team'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='cb_team_source_external_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='startingpitcher',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='cb_pitcher_source_external_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='cb_game_source_external_id_unique'),
        ),
    ]
