# Generated by Django 5.2.11 on 2026-02-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfeedback',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
