# Generated by Django 5.2.11 on 2026-02-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_partnerfeedback_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerfeedback',
            name='is_archived',
        ),
    ]
