# Generated by Django 5.2.11 on 2026-04-27 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0005_oddssnapshot_is_derived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('tight_spread', 'Tight Spread'), ('large_favorite', 'Large Favorite')], db_index=True, max_length=30)),
                ('spread', models.FloatField()),
                ('favorite_team_name', models.CharField(blank=True, max_length=120)),
                ('underdog_team_name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(db_index=True, default='odds_api', max_length=20)),
                ('source_quality', models.CharField(default='primary', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spread_opportunities', to='mlb.game')),
                ('odds_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spread_opportunities', to='mlb.oddssnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['game', '-created_at'], name='mlb_spreado_game_id_fcf852_idx'), models.Index(fields=['signal_type', '-created_at'], name='mlb_spreado_signal__a0ad67_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'odds_snapshot', 'signal_type'), name='uniq_spread_signal_per_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='TotalOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('high_scoring', 'High Scoring'), ('low_scoring', 'Low Scoring')], db_index=True, max_length=30)),
                ('total', models.FloatField()),
                ('source', models.CharField(db_index=True, default='odds_api', max_length=20)),
                ('source_quality', models.CharField(default='primary', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_opportunities', to='mlb.game')),
                ('odds_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_opportunities', to='mlb.oddssnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['game', '-created_at'], name='mlb_totalop_game_id_0acb9b_idx'), models.Index(fields=['signal_type', '-created_at'], name='mlb_totalop_signal__4bf90e_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'odds_snapshot', 'signal_type'), name='uniq_total_signal_per_snapshot')],
            },
        ),
    ]
