# Generated by Django 5.2.11 on 2026-04-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0006_spreadopportunity_totalopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadopportunity',
            name='historical_win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spreadopportunity',
            name='is_lean',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='spreadopportunity',
            name='outcome',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('push', 'Push')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='spreadopportunity',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spreadopportunity',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalopportunity',
            name='historical_win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalopportunity',
            name='is_lean',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='totalopportunity',
            name='outcome',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('push', 'Push')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='totalopportunity',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalopportunity',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='spreadopportunity',
            index=models.Index(fields=['outcome'], name='mlb_spreado_outcome_d18b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='spreadopportunity',
            index=models.Index(fields=['is_lean'], name='mlb_spreado_is_lean_af7097_idx'),
        ),
        migrations.AddIndex(
            model_name='totalopportunity',
            index=models.Index(fields=['outcome'], name='mlb_totalop_outcome_9a9fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='totalopportunity',
            index=models.Index(fields=['is_lean'], name='mlb_totalop_is_lean_aa14de_idx'),
        ),
    ]
