# Generated by Django 5.2.11 on 2026-04-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0007_spreadopportunity_historical_win_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadopportunity',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='spreadopportunity',
            name='roi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalopportunity',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='totalopportunity',
            name='roi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='spreadopportunity',
            index=models.Index(fields=['is_recommended'], name='mlb_spreado_is_reco_cdfe7c_idx'),
        ),
        migrations.AddIndex(
            model_name='totalopportunity',
            index=models.Index(fields=['is_recommended'], name='mlb_totalop_is_reco_d56e60_idx'),
        ),
    ]
