# Generated by Django 5.2.11 on 2026-08-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0011_relieverappearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True, help_text='Wall-clock timestamp of the poll that first saw THIS specific lineup for this (game, team). Never overwritten.')),
                ('players', models.JSONField(default=list)),
                ('lineup_state', models.CharField(choices=[('unknown', 'Unknown'), ('confirmed', 'Confirmed pregame'), ('updated_after_confirmation', 'Updated after confirmation'), ('post_first_pitch', 'Observed after first pitch')], db_index=True, default='confirmed', max_length=32)),
                ('source', models.CharField(choices=[('mlb_stats_api', 'MLB Stats API'), ('odds_api', 'Odds API'), ('manual', 'Manual')], default='mlb_stats_api', max_length=30)),
                ('data_confidence', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='high', max_length=6)),
                ('raw_snapshot', models.JSONField(blank=True, default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_lineups', to='mlb.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_lineups', to='mlb.team')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['game', 'team', 'observed_at'], name='mlb_confirm_game_id_23bee3_idx'), models.Index(fields=['game', '-observed_at'], name='mlb_confirm_game_id_68eebb_idx'), models.Index(fields=['team', '-observed_at'], name='mlb_confirm_team_id_5423d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'team', 'observed_at'), name='mlb_confirmed_lineup_unique_observation')],
            },
        ),
    ]
