# Generated by Django 5.2.11 on 2026-08-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0012_confirmedlineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBattingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(db_index=True)),
                ('season', models.IntegerField(db_index=True)),
                ('plate_appearances', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('sac_flies', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('obp_reported', models.FloatField(blank=True, null=True)),
                ('slg_reported', models.FloatField(blank=True, null=True)),
                ('ops_reported', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('mlb_stats_api', 'MLB Stats API'), ('odds_api', 'Odds API'), ('manual', 'Manual')], default='', max_length=30)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_snapshots', to='mlb.team')),
            ],
            options={
                'ordering': ['-as_of_date'],
                'indexes': [models.Index(fields=['team', '-as_of_date'], name='mlb_teambat_team_id_15b0ca_idx'), models.Index(fields=['season', '-as_of_date'], name='mlb_teambat_season_26f6e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'as_of_date'), name='mlb_team_batting_snapshot_team_asof_unique')],
            },
        ),
    ]
