# Generated by Django 5.2.11 on 2026-02-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
