# Generated by Django 5.2.11 on 2026-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0004_oddssnapshot_movement_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddssnapshot',
            name='odds_source',
            field=models.CharField(choices=[('odds_api', 'The Odds API'), ('espn', 'ESPN Fallback'), ('manual', 'Manual Entry'), ('cached', 'Cached')], db_index=True, default='odds_api', max_length=20),
        ),
        migrations.AddField(
            model_name='oddssnapshot',
            name='source_quality',
            field=models.CharField(choices=[('primary', 'Primary'), ('fallback', 'Fallback'), ('stale', 'Stale'), ('unavailable', 'Unavailable')], default='primary', max_length=15),
        ),
    ]
