# Generated by Django 5.2.11 on 2026-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0005_oddssnapshot_odds_source_oddssnapshot_source_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddssnapshot',
            name='is_derived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
