# Generated by Django 5.2.11 on 2026-04-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0006_oddssnapshot_is_derived'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='elo_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='elo_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
