# Generated by Django 5.2.11 on 2026-02-08 16:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbb', '0003_team_primary_color'),
        ('cfb', '0003_team_primary_color'),
        ('golf', '0003_alter_golfer_options_golfer_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockBet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('cfb', 'College Football'), ('cbb', 'College Basketball'), ('golf', 'Golf')], max_length=4)),
                ('bet_type', models.CharField(choices=[('moneyline', 'Moneyline'), ('spread', 'Spread'), ('total', 'Total'), ('outright', 'Outright Winner'), ('top_5', 'Top 5 Finish'), ('top_10', 'Top 10 Finish'), ('top_20', 'Top 20 Finish'), ('make_cut', 'Make the Cut'), ('matchup', 'Head-to-Head Matchup')], max_length=10)),
                ('selection', models.CharField(max_length=200)),
                ('odds_american', models.IntegerField()),
                ('implied_probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('stake_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('simulated_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('push', 'Push')], default='pending', max_length=7)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('model_source', models.CharField(choices=[('house', 'House Model'), ('user', 'User Model')], default='house', max_length=5)),
                ('expected_edge', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('review_flag', models.CharField(blank=True, choices=[('repeat', 'Would Repeat'), ('avoid', 'Would Avoid')], max_length=6)),
                ('review_notes', models.TextField(blank=True)),
                ('cbb_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_bets', to='cbb.game')),
                ('cfb_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_bets', to='cfb.game')),
                ('golf_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_bets', to='golf.golfevent')),
                ('golf_golfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_bets', to='golf.golfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='MockBetSettlementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=7)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('mock_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_logs', to='mockbets.mockbet')),
            ],
            options={
                'ordering': ['-settled_at'],
            },
        ),
    ]
