# Generated by Django 5.2.11 on 2026-04-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_baseball', '0001_initial'),
        ('mlb', '0001_initial'),
        ('mockbets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockbet',
            name='college_baseball_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_bets', to='college_baseball.game'),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='mlb_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_bets', to='mlb.game'),
        ),
        migrations.AlterField(
            model_name='mockbet',
            name='sport',
            field=models.CharField(choices=[('cfb', 'College Football'), ('cbb', 'College Basketball'), ('golf', 'Golf'), ('mlb', 'MLB'), ('college_baseball', 'College Baseball')], max_length=20),
        ),
    ]
