# Generated by Django 5.2.11 on 2026-04-21 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bettingrecommendation'),
        ('mockbets', '0002_mockbet_college_baseball_game_mockbet_mlb_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockbet',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_bets', to='core.bettingrecommendation'),
        ),
    ]
