# Generated by Django 5.2.11 on 2026-04-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockbets', '0003_mockbet_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockbet',
            name='recommendation_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='recommendation_status',
            field=models.CharField(blank=True, choices=[('', ''), ('recommended', 'Recommended'), ('not_recommended', 'Not Recommended')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='recommendation_tier',
            field=models.CharField(blank=True, choices=[('', ''), ('elite', 'Elite'), ('strong', 'Strong'), ('standard', 'Standard')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='status_reason',
            field=models.CharField(blank=True, choices=[('', ''), ('low_edge', 'Low Edge'), ('high_juice', 'High Juice Risk'), ('marginal', 'Marginal')], default='', max_length=20),
        ),
    ]
