# Generated by Django 5.2.11 on 2026-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockbets', '0004_mockbet_recommendation_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockbet',
            name='confidence_miss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Signed gap between snapshot confidence and market implied %', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='edge_miss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot edge (pp) that did not pay off', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('', ''), ('variance', 'Bad Luck'), ('model_error', 'Model Miss'), ('market_movement', 'Market Misread'), ('bad_edge', 'Weak Edge'), ('unknown', 'Unknown')], default='', max_length=20),
        ),
    ]
