# Generated by Django 5.2.11 on 2026-04-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockbets', '0005_mockbet_confidence_miss_mockbet_edge_miss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockbet',
            name='closing_odds_american',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='clv_cents',
            field=models.FloatField(blank=True, help_text='Decimal-odds delta (bet_dec - close_dec). Positive = beat close.', null=True),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='clv_direction',
            field=models.CharField(blank=True, choices=[('', ''), ('positive', 'Positive'), ('negative', 'Negative')], default='', max_length=10),
        ),
    ]
