# Generated by Django 5.2.11 on 2026-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockbets', '0006_mockbet_closing_odds_american_mockbet_clv_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockbet',
            name='is_system_generated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mockbet',
            name='odds_source',
            field=models.CharField(choices=[('odds_api', 'Odds API'), ('espn', 'ESPN'), ('manual', 'Manual'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
    ]
