# Generated by Django 5.2.11 on 2026-02-07 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('cbb', '0001_initial'),
        ('cfb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresultsnapshot',
            name='cbb_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='cbb.game'),
        ),
        migrations.AddField(
            model_name='usergameinteraction',
            name='cbb_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='cbb.game'),
        ),
        migrations.AlterField(
            model_name='modelresultsnapshot',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='cfb.game'),
        ),
        migrations.AlterField(
            model_name='usergameinteraction',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='cfb.game'),
        ),
    ]
