# Generated by Django 5.2.11 on 2026-04-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_modelresultsnapshot_cbb_game_and_more'),
        ('college_baseball', '0001_initial'),
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresultsnapshot',
            name='college_baseball_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='college_baseball.game'),
        ),
        migrations.AddField(
            model_name='modelresultsnapshot',
            name='mlb_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='mlb.game'),
        ),
        migrations.AddField(
            model_name='usergameinteraction',
            name='college_baseball_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='college_baseball.game'),
        ),
        migrations.AddField(
            model_name='usergameinteraction',
            name='mlb_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='mlb.game'),
        ),
    ]
