# Generated by Django 5.2.11 on 2026-04-27 23:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_modelresultsnapshot_college_baseball_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.CharField(choices=[('all', 'All sports'), ('cfb', 'CFB'), ('cbb', 'CBB'), ('mlb', 'MLB'), ('college_baseball', 'College Baseball')], default='all', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('games_evaluated', models.IntegerField(default=0)),
                ('games_skipped', models.IntegerField(default=0)),
                ('is_approximate', models.BooleanField(default=False, help_text='True when any games were reconstructed using current ratings instead of stored ModelResultSnapshot.house_prob.')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
