# Generated by Django 5.2.11 on 2026-04-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_backtestrun'),
        ('cbb', '0007_team_elo_last_updated_team_elo_rating'),
        ('cfb', '0007_team_elo_last_updated_team_elo_rating'),
        ('college_baseball', '0006_team_elo_last_updated_team_elo_rating'),
        ('mlb', '0009_team_elo_last_updated_team_elo_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.CharField(choices=[('cfb', 'CFB'), ('cbb', 'CBB'), ('mlb', 'MLB'), ('college_baseball', 'College Baseball')], db_index=True, max_length=20)),
                ('pre_rating', models.FloatField()),
                ('post_rating', models.FloatField()),
                ('k_factor', models.FloatField()),
                ('is_home', models.BooleanField()),
                ('won', models.BooleanField()),
                ('margin', models.IntegerField(blank=True, null=True)),
                ('margin_multiplier', models.FloatField(default=1.0)),
                ('cbb_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='cbb.game')),
                ('cbb_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='cbb.team')),
                ('cfb_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='cfb.game')),
                ('cfb_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='cfb.team')),
                ('college_baseball_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='college_baseball.game')),
                ('college_baseball_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='college_baseball.team')),
                ('mlb_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='mlb.game')),
                ('mlb_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='mlb.team')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['sport', 'cfb_game'], name='analytics_t_sport_ff6280_idx'), models.Index(fields=['sport', 'cbb_game'], name='analytics_t_sport_edb1a2_idx'), models.Index(fields=['sport', 'mlb_game'], name='analytics_t_sport_e3cd16_idx'), models.Index(fields=['sport', 'college_baseball_game'], name='analytics_t_sport_21738c_idx')],
            },
        ),
    ]
