# Generated by Django 5.2.11 on 2026-04-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_teamelohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='rating_mode',
            field=models.CharField(choices=[('static', 'Static (team.rating)'), ('elo', 'Dynamic Elo')], db_index=True, default='static', max_length=10),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20),
        ),
    ]
