# Generated by Django 5.2.11 on 2026-05-14 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_backtestrun_error_message_backtestrun_finished_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('overall_score', models.FloatField(db_index=True)),
                ('band', models.CharField(choices=[('strong', 'Strong (≥75)'), ('healthy', 'Healthy (50–74)'), ('watch', 'Watch (25–49)'), ('intervene', 'Intervene (<25)')], db_index=True, help_text='Derived from overall_score at capture time.', max_length=10)),
                ('dimension_scores', models.JSONField(default=dict)),
                ('supporting_data', models.JSONField(default=dict)),
                ('rating_mode_active', models.CharField(choices=[('static', 'Static (team.rating)'), ('elo', 'Dynamic Elo')], default='static', max_length=10)),
                ('calibration_state', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['-captured_at', 'rating_mode_active'], name='analytics_r_capture_267484_idx'), models.Index(fields=['band', '-captured_at'], name='analytics_r_band_d62bcd_idx')],
            },
        ),
    ]
