# Generated by Django 5.2.11 on 2026-08-23 00:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_recommendationhealthsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BullpenBackfillRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('historical', 'Historical Backfill'), ('daily', 'Daily Refresh')], default='historical', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=15)),
                ('phase', models.CharField(choices=[('starting', 'Starting'), ('ingest_appearances', 'Ingesting appearances'), ('build_snapshots', 'Building snapshots'), ('done', 'Done')], default='starting', max_length=25)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('games_seen', models.IntegerField(default=0)),
                ('boxscores_fetched', models.IntegerField(default=0)),
                ('appearances_created', models.IntegerField(default=0)),
                ('appearances_updated', models.IntegerField(default=0)),
                ('appearances_skipped_existing', models.IntegerField(default=0)),
                ('boxscore_errors', models.IntegerField(default=0)),
                ('snapshots_created', models.IntegerField(default=0)),
                ('snapshots_skipped_existing', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log_tail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'kind'], name='analytics_b_created_15eea6_idx')],
            },
        ),
    ]
