# Generated by Django 5.2.11 on 2026-08-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_bullpenbackfillrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullpenbackfillrun',
            name='failure_summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bullpenbackfillrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], db_index=True, default='pending', max_length=25),
        ),
    ]
