# Generated by Django 5.2.11 on 2026-08-23 01:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_bullpenbackfillrun_failure_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BullpenExperimentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=15)),
                ('days', models.IntegerField(default=180)),
                ('blend_weight', models.FloatField(default=0.55)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress_variant', models.CharField(blank=True, default='', max_length=8)),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('failure_summary', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log_tail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
