# Generated by Django 5.2.11 on 2026-08-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_bullpenexperimentrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullpenexperimentrun',
            name='kind',
            field=models.CharField(choices=[('experiment', 'A/B/C Replay Experiment'), ('attribution', 'Attribution + Salvage Study')], db_index=True, default='experiment', max_length=20),
        ),
    ]
