# Generated by Django 5.2.11 on 2026-08-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_bullpenexperimentrun_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullpenexperimentrun',
            name='progress_variant',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
