# Generated by Django 5.2.11 on 2026-08-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_alter_bullpenexperimentrun_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullpenexperimentrun',
            name='kind',
            field=models.CharField(choices=[('experiment', 'A/B/C Replay Experiment'), ('attribution', 'Attribution + Salvage Study'), ('veto_walkforward', 'Bullpen Veto Walk-Forward'), ('offense_replay', 'Team Offense Replay')], db_index=True, default='experiment', max_length=20),
        ),
    ]
