# Generated by Django 5.2.11 on 2026-08-23 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_alter_bullpenexperimentrun_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullpenexperimentrun',
            name='kind',
            field=models.CharField(choices=[('experiment', 'A/B/C Replay Experiment'), ('attribution', 'Attribution + Salvage Study'), ('veto_walkforward', 'Bullpen Veto Walk-Forward'), ('offense_replay', 'Team Offense Replay'), ('offense_isolated', 'Team Offense — Isolated Predictive Value'), ('offense_v2_replay', 'Team Offense V2 Replay (Bounded)')], db_index=True, default='experiment', max_length=20),
        ),
        migrations.CreateModel(
            name='TeamBattingBackfillRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('historical', 'Historical Backfill'), ('daily', 'Daily Refresh')], default='historical', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], db_index=True, default='pending', max_length=25)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetches_attempted', models.IntegerField(default=0)),
                ('fetches_succeeded', models.IntegerField(default=0)),
                ('fetches_empty', models.IntegerField(default=0)),
                ('fetches_errored', models.IntegerField(default=0)),
                ('snapshots_created', models.IntegerField(default=0)),
                ('snapshots_updated', models.IntegerField(default=0)),
                ('teams_seen', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('failure_summary', models.CharField(blank=True, default='', max_length=500)),
                ('log_tail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'kind'], name='analytics_t_created_515d87_idx')],
            },
        ),
    ]
