# Generated by Django 5.2.11 on 2026-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_alter_bullpenexperimentrun_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambattingbackfillrun',
            name='only_missing',
            field=models.BooleanField(default=False),
        ),
    ]
