# Generated by Django 5.2.11 on 2026-08-24 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_teambattingbackfillrun_only_missing'),
        ('mlb', '0013_teambattingsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardValidationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_version', models.CharField(choices=[('v3_2', 'V3.2 (Recent Form ON, blend 0.55, 0.62/7pp)')], db_index=True, default='v3_2', max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('minutes_to_first_pitch', models.IntegerField(help_text='Wall-clock minutes between captured_at and first_pitch.')),
                ('decision_class', models.CharField(choices=[('recommended', 'Recommended (status=recommended, lane=core)'), ('potential', 'Potential (status=recommended, lane=qualified)'), ('not_recommended', 'Not Recommended'), ('no_signal', 'No Signal (no odds, insufficient data)')], db_index=True, max_length=20)),
                ('pick', models.CharField(blank=True, default='', max_length=200)),
                ('pick_side', models.CharField(blank=True, default='', help_text="'home' / 'away' / '' when no_signal", max_length=5)),
                ('odds_american', models.IntegerField(blank=True, null=True)),
                ('odds_source', models.CharField(choices=[('odds_api', 'The Odds API'), ('espn', 'ESPN (fallback)'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('odds_captured_at', models.DateTimeField(blank=True, null=True)),
                ('raw_model_prob', models.FloatField(blank=True, null=True)),
                ('final_model_prob', models.FloatField(blank=True, null=True)),
                ('market_prob', models.FloatField(blank=True, null=True)),
                ('edge_pp', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('status_reason', models.CharField(blank=True, default='', max_length=32)),
                ('tier', models.CharField(blank=True, default='', max_length=16)),
                ('lane', models.CharField(blank=True, default='', max_length=16)),
                ('risk_flags', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(default=0)),
                ('is_secondary', models.BooleanField(default=False)),
                ('movement_class', models.CharField(blank=True, default='', max_length=16)),
                ('movement_score', models.FloatField(blank=True, null=True)),
                ('movement_supports_pick', models.BooleanField(default=False)),
                ('market_warning', models.BooleanField(default=False)),
                ('feature_contributions', models.JSONField(blank=True, default=dict)),
                ('lineup_state', models.CharField(choices=[('unknown', 'Unknown'), ('projected', 'Projected'), ('confirmed', 'Confirmed'), ('updated_after_confirmation', 'Updated After Confirmation')], default='unknown', max_length=32)),
                ('lineup_snapshot_ref', models.CharField(blank=True, default='', help_text='Reference (id / timestamp) of the latest legitimate pregame lineup snapshot at capture time.', max_length=64)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('won', models.BooleanField(blank=True, help_text='None until settled; True/False after; None for push.', null=True)),
                ('profit_per_dollar', models.FloatField(blank=True, help_text='Hypothetical flat-stake $1 profit at captured odds.', null=True)),
                ('closing_market_prob', models.FloatField(blank=True, null=True)),
                ('clv_pp', models.FloatField(blank=True, help_text='Closing-line value in probability points (positive = beat the close).', null=True)),
                ('home_score_at_settlement', models.IntegerField(blank=True, null=True)),
                ('away_score_at_settlement', models.IntegerField(blank=True, null=True)),
                ('mlb_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3_2_forward_snapshots', to='mlb.game')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['engine_version', '-captured_at'], name='analytics_f_engine__9337fd_idx'), models.Index(fields=['decision_class', '-captured_at'], name='analytics_f_decisio_69c437_idx'), models.Index(fields=['-captured_at', 'engine_version'], name='analytics_f_capture_ac90f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('mlb_game', 'engine_version'), name='fwd_val_snapshot_game_engine_unique')],
            },
        ),
    ]
