# Generated by Django 5.2.11 on 2026-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbb', '0002_game_away_score_game_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
