# Generated by Django 5.2.11 on 2026-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbb', '0003_team_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddssnapshot',
            name='movement_class',
            field=models.CharField(blank=True, choices=[('noise', 'Noise'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('sharp', 'Sharp Action')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='oddssnapshot',
            name='movement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oddssnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('raw', 'Raw Pull'), ('significant', 'Significant Move'), ('closing', 'Closing Line'), ('bet_context', 'Bet Context')], db_index=True, default='raw', max_length=20),
        ),
        migrations.AddIndex(
            model_name='oddssnapshot',
            index=models.Index(fields=['game', '-captured_at'], name='cbb_oddssna_game_id_bbe836_idx'),
        ),
        migrations.AddIndex(
            model_name='oddssnapshot',
            index=models.Index(fields=['snapshot_type', '-captured_at'], name='cbb_oddssna_snapsho_abcf28_idx'),
        ),
    ]
